language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    CODECOV_TOKEN='5ec78188-021d-4bcb-8eb6-5b94383b34ec'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vitalijvictor@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
